config/routes.rb
Rails.application.routes.draw do

  resources :bjond_registrations

  scope '/bjond-app' do
    get  '/services/' => 'bjondservices#index'
    get  '/services/edit/:id' => 'bjondservices#edit'
    patch  '/services/:id' => 'bjondservices#update'
    get  '/services/schema' => 'bjondservices#get_schema'
    get  '/services/register' => 'bjondservices#register'
    post '/services/:groupid/register' => 'bjondservices#register_group_endpoint'
    get  '/services/:groupid/read' => 'bjondservices#get_group_configuration'
    post '/services/:groupid/configure' => 'bjondservices#configure_group_endpoint'
    get  '/services/:groupid/:userid/read' => 'bjondservices#get_user_configuration'
    get  '/services/schema/user' => 'bjondservices#get_user_schema'
  end
end

app/models/bjond_registration.rb
include BjondApi
require 'attr_encrypted'
require 'resolv'

class BjondRegistration < ActiveRecord::Base
  has_many :bjond_services, :dependent => :destroy
  
  
  attr_encrypted :encryption_key, key: ENV[BjondApi::BjondAppConfig.instance.encryption_key_name]

  def self.find_registration_by_remote_request(request)
    ip = Resolv.getaddress(request.ip)
    result = BjondRegistration.find_by_ip(ip)
    if (!result.nil?)
      return result
    end
    host = Resolv.getname(ip)
    host_result = BjondRegistration.find_by_host(host)
    if (!host_result.nil?)
      return host_result
    end

    puts 'Warning! No BjondRegistration found for ip: ' + ip + '. This IP resolves to ' + host + 'Trying most recent registration. '
    puts 'Incoming request parameters: '
    ap request
    return BjondRegistration.last
  end

end

app/models/bjond_service.rb
class BjondService < ActiveRecord::Base
  belongs_to :bjond_registration
end

app/controllers/bjond_registrations_controller.rb
class BjondRegistrationsController < ApplicationController
  before_action :set_bjond_registration, only: [:show, :edit, :update, :destroy]

  require 'bjond-api'
  require 'uri'

  # GET /bjond_registrations
  def index
    @bjond_registrations = BjondRegistration.all
    @app_info = BjondApi::BjondAppConfig.instance.active_definition
  end

  # GET /bjond_registrations/1
  def show
    @services = BjondService.where(:bjond_registration_id => @bjond_registration.id)
  end

  # GET /bjond_registrations/new
  def new
    @bjond_registration = BjondRegistration.new
  end

  # GET /bjond_registrations/1/edit
  def edit
  end

  # POST /bjond_registrations
  def create
    @bjond_registration = BjondRegistration.find_or_initialize_by(bjond_registration_params)
    uri = URI.parse(@bjond_registration.server)
    @bjond_registration.ip = Resolv.getaddress(uri.host)
    @bjond_registration.host = Resolv.getname(@bjond_registration.ip)
    response = BjondApi.register_app(BjondApi::BjondAppConfig.instance.active_definition, @bjond_registration.server)

    if (response.status == 500) 
      throw "Unable to register with Bjond. \n" + response.body
    end


    if @bjond_registration.save
      redirect_to @bjond_registration, notice: 'Bjönd registration was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bjond_registrations/1
  def update
    if @bjond_registration.update(bjond_registration_params)
      redirect_to @bjond_registration, notice: 'Bjönd registration was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bjond_registrations/1
  def destroy
    @bjond_registration.destroy
    redirect_to bjond_registrations_url, notice: 'Bjönd registration was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bjond_registration
      @bjond_registration = BjondRegistration.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def bjond_registration_params
      params.require(:bjond_registration).permit(:server, :encryption_key, :ip, :host)
    end
end

app/controllers/bjondservices_controller.rb
class BjondservicesController < ApplicationController 

  require 'bjond-api'
  require 'syruppay_jose'
  require 'bjond-jwt'
  include BjondJwt

  skip_before_filter :verify_authenticity_token, :only => [:get_schema, :register_group_endpoint, :configure_group_endpoint]

  def index
    @app_info = BjondApi::BjondAppConfig.instance.active_definition
  end

  def edit
    @bjondservice = BjondService.find(params[:id])
  end

  def update
    @bjondservice = BjondService.find(params[:id])
    if @bjondservice.update(bjondservices_params)
      redirect_to @bjondservice.bjond_registration, notice: 'Bjond services was successfully updated.'
    else
      render @bjondservice.bjond_registration
    end
  end

  def register
    registration = BjondRegistration.find_by_id(params[:id])
    if (!registration.nil?)
      response = BjondApi.register_app(BjondApi::BjondAppConfig.instance.active_definition, registration.server)
      if (response.status === 200 )
        render :json => {
          :status => 'Updated'
        }
      else
        raise "Failed to update.\n" + response.body
      end
    else
      render :json => {
        :status => 'Registration not found'
      }
    end
  end



  def register_group_endpoint
    registration = get_registration
    service = BjondService.find_or_initialize_by(:group_id => params[:groupid], :bjond_registration_id => registration.id)
    if (service.endpoint != params[:endpoint])
      service.endpoint = params[:endpoint]
      service.save
    end
    render :json => service
  end

  ################ Encrypted Communication w Bjond servers ################
  def configure_group_endpoint
    puts 'configure_group_endpoint'
    bjond_registration = get_registration
    result = jwt_decode_payload_and_return_json(request.raw_post, bjond_registration)
    BjondApi::BjondAppConfig.instance.configure_group(result, bjond_registration, params[:groupid])
    render :json => {
      :status => 'OK'
    }.to_json
  end

  def get_schema
    puts 'get_schema'
    render :json => jwt_encode_payload(BjondApi::BjondAppConfig.instance.group_configuration_schema,
                                       get_registration)
  end

  def get_group_configuration
    bjond_registration = get_registration
    payload = BjondApi::BjondAppConfig.instance.get_group_configuration(bjond_registration, params[:groupid])
    render :json => jwt_encode_payload(payload.to_json, bjond_registration)
  end

  def get_registration
    ap params
    registration = nil
    if (params[:environment])
      puts '**************** Looking up registration by environment'
      registration = BjondRegistration.find_by_server(params[:environment])
    end

    if (registration.nil?)
      puts 'searching by remote request'
      registration = BjondRegistration.find_registration_by_remote_request(request)
    end
    ap registration
    return registration
  end

  def get_user_configuration
    bjond_registration = get_registration
    payload = BjondApi::BjondAppConfig.instance.get_user_configuration(bjond_registration)
    render :json => jwt_encode_payload(payload.to_json, bjond_registration)
  end

  def get_user_schema
    puts 'get_user_schema'
    bjond_registration = get_registration
    payload = jwt_encode_payload(BjondApi::BjondAppConfig.instance.user_configuration_schema, bjond_registration)
    render :json => payload
  end

  # Only allow a trusted parameter "white list" through.
  private
    def bjondservices_params
      params.require(:bjond_service).permit(:group_id, :endpoint,)
    end

end

app/helpers/bjond_jwt_helper.rb
module BjondJwtHelper
  def jwt_encode_payload(json, bjond_registration)
    payload = {
      :json => json,
      :iss => 'Bjönd, Inc.',
      :aud => ENV['BJOND_ADAPTER_AUDIENCE'],
      :exp => Time.now.to_i + 10*3600,
      :nbf => Time.now.to_i - 2*3600,
      :sub => ENV['BJOND_ADAPTER_SUBJECT']
    }.to_json
    header = {:alg => 'A128KW', :enc => 'A128CBC-HS256'}
    puts "**************************************************"
    puts bjond_registration.encryption_key
    return SyrupPay::JsonEncryptionCompactSerialization.serialization(Base64.decode64(bjond_registration.encryption_key), header, payload)
  end

  def jwt_decode_payload_and_return_json(token, bjond_registration)
    claims_json = SyrupPay::CompactDeserialization.deserialization(Base64.decode64(bjond_registration.encryption_key), token)
    claims = JSON.parse(claims_json)
    return JSON.parse(claims['json'][0])
  end
end

app/views/bjond_registrations/_form.html.erb
<%= form_for(@bjond_registration) do |f| %>
  <% if @bjond_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bjond_registration.errors.count, "error") %> prohibited this bjond_registration from being saved:</h2>

      <ul>
      <% @bjond_registration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class="label">
      Server:
    </span>
    <%= f.text_field :server %>
  </div>
  <div class="field">
    <span class="label">
      IP
    </span>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <span class="label">
      Host
    </span>
    <%= f.text_field :host %>
  </div>

  <div class="field">
    <span class="label">
      API Key / Encryption Key
    </span>
    <%= f.text_field :encryption_key %>
  </div>
  <div class="actions">
    <%= f.submit "Update Bjönd Registration" %>
  </div>
<% end %>

app/views/bjond_registrations/edit.html.erb
<div class="edit-registrations">
  <h1 class="app-info-header">Editing Bjönd Registration</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @bjond_registration %> |
  <%= link_to 'Back', bjond_registrations_path %>
</div>

app/views/bjond_registrations/index.html.erb
<div class="bjond-registration">
  <p id="notice"><%= notice %></p>

  <div class="bjond-app-title">Listing Bjönd Registrations</div>


  <div class="bjond-registration-list">
    <% if @bjond_registrations.count > 0 %>
      <table class="bjond-table">
        <thead>
          <tr class="bjond-table-row">
            <th>Server</th>
            <th>Encrypted Encryption Key</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @bjond_registrations.each do |bjond_registration| %>
            <tr class="bjond-table-row">
              <td><%= bjond_registration.server %></td>
              <td><%= bjond_registration.encrypted_encryption_key %></td>
              <td><%= link_to 'Show', bjond_registration %></td>
              <td><%= link_to 'Edit', edit_bjond_registration_path(bjond_registration) %></td>
              <td><%= link_to 'Destroy', bjond_registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="non-available">
        No registrations
      </div>
    <% end %>

    <div class="new-registration-link">
      <%= link_to 'New Bjönd registration', new_bjond_registration_path %>
    </div>

  </div>

  <%= render 'shared/app_info.html' %>
</div>

app/views/bjond_registrations/new.html.erb
<div class="new-registrations">

  <h1 class="app-info-header">New Bjönd Registration</h1>

  <%= form_for(@bjond_registration) do |f| %>
    <% if @bjond_registration.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@bjond_registration.errors.count, "error") %> prohibited this bjond_registration from being saved:</h2>

        <ul>
        <% @bjond_registration.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <span class="label">
        Enter server name
      </span>
      <%= f.text_field :server %>
      
      <div class="additional-info">
        (e.g. https://test.bjondhealth.com)
      </div>
    </div>

    <div class="actions">
      <%= f.submit "Register with Bjönd"%>
    </div>
  <% end %>

  </br>
  <%= link_to 'Back', bjond_registrations_path %>

</div>

app/views/bjond_registrations/show.html.erb
<div class="show-registrations" ng-controller="registrationsController">
  <p id="notice"><%= notice %></p>

  <h3>
    Registration Info
  </h3>

  <p>
    <strong>Server:</strong>
    <%= @bjond_registration.server %>
  </p>

  <p>
    <strong>Host:</strong>
    <%= @bjond_registration.host %>
  </p>

  <p>
    <strong>IP:</strong>
    <%= @bjond_registration.ip %>
  </p>


  <%- if (@bjond_registration.encrypted_encryption_key) %>
    <div class="encryption-key-found">
      <p>
        <strong>API Key / Encryption Key (encrypted):</strong>
        <%= @bjond_registration.encrypted_encryption_key %>
      </p>
    </div>
  <% else %>
    <p class="not-found">
      Please log in to the Bjönd server and locate the encryption key. You must be a tenant administratior. You will find this information on the 'Develop' tab of the system settings. Once you find this information, <%= link_to 'add it here', edit_bjond_registration_path(@bjond_registration) %>.
    </p>

  <% end %>

  <p>
    <strong>ID:</strong>
    <%= @bjond_registration.id %>
  </p>


  <button class="btn register" ng-click="register(<%= @bjond_registration.id %>)">
    Update Registration
  </button>
  </br>
  <%= link_to 'Edit', edit_bjond_registration_path(@bjond_registration) %> |
  <%= link_to 'Back', bjond_registrations_path %>


  <%- if @services.count > 0 %>
    <h3>
      Bjönd Services associated with this Registration
    </h3>

    <div class="bjond-info">
      <p>
        <strong>Note:</strong></br>
        Please verify that the service endpoints below have the correct host.
        If the host (preceeding /server-core/services..) is incorrect, the Bjönd Server
        may need to set its OPENSHIFT_PUBLIC_URL environment variable. Once this
        environment variable is re-set (and the Bjönd Server restarted), please
        re-register the affected services.
      </p>
      <p>
        The endpoints may also be manually updated by modifying the Bjönd Service.
        Please exercise caution when modifying these fields.
      </p>
    </div>

    <%- @services.each do |service| %>
      <div class="bjond-service">
        <p>
          <strong>ID:</strong>
          <%= service.id %>
        </p>
        <p>
          <strong>Group ID:</strong>
          <%= service.group_id %>
        </p>

        <p>
          <strong>Endpoint:</strong>
          <%= service.endpoint %>
        </p>

        <p>
          <%= link_to "Modify Bjönd Service", "/bjond-app/services/edit/#{service.id}"%>
        </p>

      </div>
    <% end %>
  <% end %>
</div>

app/views/bjondservices/edit.html.erb
<div class="edit-registrations">
  <h1 class="app-info-header">Editing Bjönd Service</h1>

  <%= form_for(@bjondservice, :url => "/bjond-app/services/#{@bjondservice.id}") do |f| %>
    <% if @bjondservice.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@bjondservice.errors.count, "error") %> prohibited this bjondservice from being saved:</h2>

        <ul>
        <% @bjondservice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <span class="label">
        Group ID:
      </span>
      <%= f.text_field :group_id %>
    </div>
    <div class="field">
      <span class="label">
        Endpoint:
      </span>
      <%= f.text_field :endpoint %>
    </div>
    
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>


</div>

app/views/bjondservices/index.html.erb
<h1 class="title" ng-controller="homeController">
  <%= @app_info.name %>
</h1>

<%= render 'shared/app_info.html' %>

app/views/shared/_app_info.html.erb
<div class="app-info">
  <div class="app-info-header">
    <%= image_tag @app_info.iconURL %>
    <h2 class="app-name"><%= @app_info.name %></h2>
  </div>


  <div class="field-wrapper">
    <div class="app-label">Description:</div>
    <div class="info"><%= @app_info.description %></div>
  </div>

  <div class="field-wrapper">
    <div class="app-label">Config URL:</div>
    <div class="info"><%= @app_info.configURL %></div>
  </div>

  <div class="field-wrapper">
    <div class="app-label">Root Endpoint:</div>
    <div class="info"><%= @app_info.rootEndpoint %></div>
  </div>

  <div class="field-wrapper">
    <div class="app-label">Author:</div>
    <div class="info"><%= @app_info.author %></div>
  </div>

  <div class="field-wrapper">
    <div class="app-label">ID:</div>
    <div class="info"><%= @app_info.id %></div>
  </div>


  </br>

  <% if @app_info.integrationEvent.count > 0 %>
    <h2> Events (Conditions) </h2>
    <div class="events">
      <% @app_info.integrationEvent.each do |event| %>
        <div class="event">
          <h4><%= event.name %></h4>
          
          <div class="field-wrapper">
            <div class="app-label">Description:</div>
            <div class="info"><%= event.description %></div>
          </div>

          <div class="field-wrapper">
            <div class="app-label">jsonKey:</div>
            <div class="info"><%= event.jsonKey %></div>
          </div>
          
          <h3>Fields:</h3>
          <div class="fields">
            <% event.fields.each do |field| %>
              <div class="field">
                <div class="field-wrapper">
                  <div class="app-label">Field Name:</div>
                  <div class="info new-section"><%= field.name %></div>
                </div>
                <div class="field-wrapper">
                  <div class="app-label">ID:</div>
                  <div class="info"><%= field.id %></div>
                </div>
                <div class="field-wrapper">
                  <div class="app-label">Json Key:</div>
                  <div class="info"><%= field.jsonKey %></div>
                </div>
                <div class="field-wrapper">
                  <div class="app-label">Field Type:</div>
                  <div class="info"><%= field.fieldType %></div>
                </div>

                <% if field.persist %>
                  <div class="field-wrapper">
                    <strong>Marked for Persistence</strong>
                  </div>
                  <div class="field-wrapper">
                    <div class="app-label">Data Type:</div>
                    <div class="info"><%= field.dataType %></div>
                  </div>
                <% elsif field.fieldType != 'Person' %>
                  <div class="field-wrapper">
                    <span>Not marked for persistence</span>
                  </div>
                <% end %>
                <% if field.identifier && field.fieldType == 'Person' %>
                  <div class="field-wrapper">
                    <strong>Event Person Identifier</strong>
                  </div>
                <% end %>
              </div>
              <hr>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

  <% else %>
    <div class="non-available">
      No events are currently available for this app.
    </div>
  <% end %>

  <% if @app_info.integrationConsequence.count > 0 %>
    <h2> Consequences </h2>
    <div class="consequences">
      <% @app_info.integrationConsequence.each do |consequence| %>
        <div class="consequence">
          <h4><%= consequence.name %></h4>

          <div class="field-wrapper">
            <div class="app-label">ID:</div>
            <div class="info"><%= consequence.id %></div>
          </div>

          <div class="field-wrapper">
            <div class="app-label">Json Key:</div>
            <div class="info"><%= consequence.jsonKey %></div>
          </div>
          <div class="field-wrapper">
            <div class="app-label">Description:</div>
            <div class="info"><%= consequence.description %></div>
          </div>

          <div class="field-wrapper">
            <div class="app-label">Webhook:</div>
            <div class="info"><%= consequence.webhook %></div>
          </div>

        </div>
      <% end %>
    </div>
  <% else %>
    <div class="consequence non-available">
      No consequences are available for this app.
    </div>
  <% end %>
</div>